### ISSUE TITLE
uYou login fix question

### ISSUE THREAD

**Issue by swaggyP36000** [BandarHL/BandarHL#4]
Hi, I wanted to reach out about this on Twitter but Twitter is giving me issues, so I'm having to ask here - I saw your login fix commit on GitHub for uYou+ and was wondering if you could turn that into its own dylib/deb so other YouTube tweaks can use it as well

**Comment by BandarHL** [comment]
https://drive.google.com/file/d/1gp2PAegV1WG9GbI8YnfcKgiA86IHfm9e/view?usp=share_link
